version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
    groups:
      github-actions-official:
        patterns:
          - "actions/*"
          - "github/*"
      github-actions-third-party:
        patterns:
          - "pnpm/*"
          - "dorny/*"
          - "SonarSource/*"
          - "cloudflare/*"
          - "amannn/*"
