sonar.projectKey=typeorm-codemod
sonar.organization=typeorm
sonar.sources=src
sonar.tests=test
sonar.exclusions=test/**/fixtures/**
sonar.javascript.lcov.reportPaths=coverage/lcov.info
sonar.qualitygate.wait=true
