import type { SidebarsConfig } from "@docusaurus/plugin-content-docs"

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */
const sidebars: SidebarsConfig = {
    // Manually defined sidebar with items in a logical order
    tutorialSidebar: [
        {
            type: "doc",
            id: "getting-started",
            label: "开始",
        },
        {
            type: "category",
            label: "数据源",
            items: [{ type: "autogenerated", dirName: "data-source" }],
        },
        {
            type: "category",
            label: "实体",
            items: [{ type: "autogenerated", dirName: "entity" }],
        },
        {
            type: "category",
            label: "关系",
            items: [{ type: "autogenerated", dirName: "relations" }],
        },
        {
            type: "category",
            label: "迁移",
            items: [{ type: "autogenerated", dirName: "migrations" }],
        },
        {
            type: "category",
            label: "使用实体管理器",
            items: [
                {
                    type: "autogenerated",
                    dirName: "working-with-entity-manager",
                },
            ],
        },
        {
            type: "category",
            label: "查询构建器",
            items: [{ type: "autogenerated", dirName: "query-builder" }],
        },
        "query-runner",
        {
            type: "category",
            label: "驱动",
            items: [{ type: "autogenerated", dirName: "drivers" }],
        },
        {
            type: "category",
            label: "指南",
            items: [{ type: "autogenerated", dirName: "guides" }],
        },
        {
            type: "category",
            label: "高级用法",
            items: [{ type: "autogenerated", dirName: "advanced-topics" }],
        },
        {
            type: "category",
            label: "帮助",
            items: [{ type: "autogenerated", dirName: "help" }],
        },
        {
            type: "category",
            label: "谷歌编程之夏",
            items: [{ type: "autogenerated", dirName: "gsoc" }],
        },
        "future-of-typeorm",
    ],
}

export default sidebars
