name: mutation-testing

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 1 * *"

jobs:
  mutation-testing:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:5.7.44
        ports:
          - "3306:3306"
        env:
          MYSQL_ROOT_PASSWORD: admin
          MYSQL_USER: username
          MYSQL_PASSWORD: password
          MYSQL_DATABASE: typeorm
      mariadb:
        image: mariadb:10.11.16
        ports:
          - "3307:3306"
        env:
          MYSQL_ROOT_PASSWORD: admin
          MYSQL_USER: username
          MYSQL_PASSWORD: password
          MYSQL_DATABASE: typeorm
      postgres:
        image: ghcr.io/naorpeled/typeorm-postgres:pg17-postgis3-pgvectorv0.8.0
        ports:
          - "5432:5432"
        env:
          POSTGRES_USER: username
          POSTGRES_PASSWORD: password
          POSTGRES_DB: typeorm
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - uses: actions/checkout@v6
      - uses: pnpm/action-setup@v4
      - uses: actions/setup-node@v6
        with:
          node-version: 24
          cache: "pnpm"
      - run: pnpm install
      - run: |
          jq 'map(select(.type | IN($ARGS.positional[])))' \
            ormconfig.sample.json \
            --args \
              "better-sqlite3" \
              "mariadb" \
              "mysql" \
              "postgres" \
              "sqljs" \
            > ormconfig.json
      - run: pnpm exec stryker run
        env:
          STRYKER_DASHBOARD_API_KEY: ${{ secrets.STRYKER_DASHBOARD_API_KEY }}

      - uses: actions/upload-artifact@v7
        with:
          name: mutation-testing
          path: ./reports/mutation/mutation.html
